CREATE TABLE people (
    `id` INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `ip` VARCHAR(255) NOT NULL,
    `code` VARCHAR(255),
    `planet` VARCHAR(255),
    `date` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)
